### ISSUE TITLE
Сделать переключение тем (светлой/тёмной)

### ISSUE THREAD

**Issue by MrDrag0nXYT** [samthezpub/labwork_swing#27]
## ДОПОЛНИТЕЛЬНО:
- Сделать динамическое переключение темы на основе той, которая установлена в ОС
(Например: если в ОС установлена тёмная тема, то и в приложении будет тёмная, если в настройках не выбрано другое)

**Comment by samthezpub** [comment]
Костя делает Форму "Настройки", а мы сделаем функционал
